# Environment
name: LSA_SAF_ENV
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - astropy=6.1
  - ipykernel=6.29.5
  - pandas=2.2.2
  - jupyter=1.0.0
  - matplotlib=3.8.4
  - numpy=1.26.4
  - scipy=1.13.0
  - scikit-learn=1.6.1
  - pybind11=2.12.0
  - cmake=3.29.3
  - gsl=2.7
  - seaborn=0.13.2
  - xgboost=2.1.4
  - imbalanced-learn=0.13.0
  - tensorflow=2.18.1
  - shap=0.47.2
#  - lightgbm=4.3.0    # 4.6.0 not on conda-forge as of June 2025
  - catboost=1.2.8
  - h5py=3.11.0
  - netCDF4=1.6.5
  - h5netcdf=1.3.0
  - xarray=2024.3.0
  - pip=24.0
  - pip:
      - datetime>=4.3
#      - fitsio==1.1.8
      - emcee==3.1.4
      - pyyaml>=6.0
      - tqdm>=4.66
      - lightgbm==4.6.0
